# Generated by Django 5.2.10 on 2026-03-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyplan',
            name='study_start_time',
            field=models.TimeField(default='09:00:00'),
        ),
    ]
